version: '3.2'

services:
    db:
        container_name: melimelo_postgres
        image: postgres:13
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            PGDATA: /srv/postgres
        volumes:
            - ./docker/pgsql/data:/srv/postgres
        ports:
            - "5432:5432"
        networks:
            - melimelo
            - postgres
        restart: unless-stopped

    pgadmin:
        container_name: melimelo_pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.local}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        ports:
            - "${PGADMIN_PORT:-8050}:80"
        networks:
            - postgres
        restart: unless-stopped

networks:
    melimelo: ~
    postgres: ~

volumes:
    postgres: